name: Build and Push Docker Image

on:
  push:
    branches:
      - devops

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thomazjoseph/node-test:latest
  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
        - name: Install AWS CLI
          run: |
            sudo apt-get update
            sudo apt-get install -y awscli

        - name: Deploy to EC2
          run: |
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@172.31.9.4 
            << EOF
            docker pull thomazjoseph/node-test:latest
            docker run -d --name node-dev -p 8080:8080 thomazjoseph/node-test:latest
            EOF
